#!/bin/bash
cd "${0%/*}" &>/dev/null
IsYes() {
    for((i=0; 1; ++i));do
        [[ "$i" -gt 0 ]] && echo "Please type either yes or no .." >&2
        echo -en "$1"
        read reply
        ([[ "$reply" != 'yes' ]] && [[ "$reply" != 'no' ]]) || break;
    done
    [[ "$reply" == 'yes' ]]
    return $?
}

declare -r DEPENDENCIES="curl:wget:mplayer"

check() {
    local IFS=':'
    for i in $DEPENDENCIES ; do
        if [[ -z "$(which "$i")" ]] ; then
            echo "$i not installed (needed by PlayMusic)" >&2
            exit 2
        fi
    done
}

check

if [[ -x '/usr/bin/PlayMusic' ]] && [[ -f '/usr/share/man/man1/PlayMusic.1.gz' ]];then
    read -p 'PlayMusic is already installed ! Do You want to uninstall it first ( this is necessary for installation ) ? '
    if IsYes $REPLY;then
        if ! /usr/bin/PlayMusic -u ; then
            # Uninstalling manually
            sudo rm '/usr/bin/PlayMusic'
            sudo rm '/usr/share/man/man1/PlayMusic.1.gz'
            if [[ -f '/etc/PlayMusic.settings' ]] ; then
                if ! IsYes 'Do you want to keep your settings ? ' ; then
                    sudo rm "$HOME/.config/PlayMusic.settings"
                fi
            fi
        fi
    else
        exit 1
    fi
fi

install() {
    echo "Installing $1 .."
    sudo cp "$1" '/usr/bin/' &&
    sudo chmod +x "/usr/bin/$1" &&
    sudo gzip "$1.1" &&
    sudo cp "$1.1.gz" '/usr/share/man/man1/' &&
    echo "Installed $1 successfully !" || {
        echo "Failed to install $1"
        exit 1
    }
}

install 'IsYes'
install 'PlayMusic'
echo "Success!"
exit 0
