#!/bin/bash
cd "${0%/*}";function IsYes { d=$(echo $1 | tr [[:upper:]] [[:lower:]]);if ([[ "${d:0:1}" == 'y' ]] && [[  "${#d}" -le 4 ]]) || [[ $d == 'ok' ]];then exit 0; else exit 1;fi; }
if [[ -x '/usr/bin/apt-get' ]];then
	echo 'Checking Needed Programs ..'
	sudo apt-get install axel mplayer2 lynx
fi;if [[ ! -x '/usr/bin/wget' ]];then echo 'Please Install wget first ( CommandLine downloader ) ..';exit 2
elif [[ ! -x '/usr/bin/mplayer' ]];then echo 'Please Install mplayer ( CommandLine media player ) ..';exit 2
elif [[ ! -x '/usr/bin/lynx' ]];then echo 'Please Install mplayer ( CommandLine browser ) ..';exit 2;fi
if [[ -x '/usr/bin/PlayMusic' ]] && [[ -f '/usr/share/man/man1/PlayMusic.1.gz' ]];then
	read -p 'PlayMusic is already installed ! Do You want to uninstall it first ( this is necessary for installation ) ? '
	if IsYes $REPLY;then
		PlayMusic -u || {
			sudo rm '/usr/bin/PlayMusic'
			sudo rm '/usr/share/man/man1/PlayMusic.1.gz'
			if [[ -f '/etc/PlayMusic.settings' ]];then
				read -p 'Do you want to keep your settings ? '
				if ! IsYes $REPLY;then sudo rm '/etc/PlayMusic.settings';fi
			fi; }
	else exit 1;fi
fi
if [[ $? == 0 ]];then
	sudo cp 'PlayMusic' '/usr/bin/'
	sudo chmod +x '/usr/bin/PlayMusic'
	sudo gzip 'PlayMusic.1'
	sudo cp 'PlayMusic.1.gz' '/usr/share/man/man1/'
	echo 'Installation Complete .. !'
else
	echo "Error ($?) !"
fi
