.TH PlayMusic 1 "25 April 2014" "1.1" "PlayMusic Manual"
.SH NAME
PlayMusic - Play/Download Music ..
.SH SYNOPSIS
.B PlayMusic
.RI [OPTIONS]
.br
.SH DESCRIPTION
Play Music is a simple entertainment utility that is made mainly for music lovers .. It can play music online, download it .. and provide you with the latest music from sites provided in the settings file .. (it can alsobe easily extended as a bash script)
.SH OPTIONS
.IP \fB\-r\fP
Play Music Recursively ..
.IP \fB\-s\fP
ReCreate the Settings File ..
.IP \fB\-u\fP
Uninstall the program ..
.IP \fB\-v\fP
View Settings File ..
.SH Exit Codes
.IP \fB0\fP
Everything went Fine ..
.IP \fB1\fP
No Music was found ..
.SH SEE ALSO
wget(1), lynx(1)
.SH BUGS
No Known Bugs ..
.SH AUTHOR
Amr Ayman (miroamr78@gmail.com)
