#!/bin/bash
cd "$HOME/Music" # So that any download will be in the music directory
function IsYes { d=$(echo $1 | tr [[:upper:]] [[:lower:]]);if ([[ "${d:0:1}" == 'y' ]] && [[  "${#d}" -le 4 ]]) || [[ $d == 'ok' ]];then exit 0; else exit 1;fi; }
declare -r settings_file='/etc/PlayMusic.settings';line_number=1;declare SITES=();declare player;declare recursive;declare FILE;declare FILE2
function create_settings_file {
	tmp_file="$HOME/Desktop/File_$RANDOM"
	cat > $tmp_file <<- EOF
		Player = mplayer
		Sites = {'http://ccmixter.org/view/media/samples/mixed'}
	EOF
	sudo mv $tmp_file '/etc/PlayMusic.settings'
	rm $tmp_file &>/dev/null # just in case ..
}
function UNINSTALL {
	read -p 'Do you want to keep settings ? '
	if ! IsYes $REPLY;then sudo rm '/etc/PlayMusic.settings';fi
	sudo rm '/usr/bin/PlayMusic'
	sudo rm '/usr/man/man1/PlayMusic.1.gz'
	echo 'Uninstallation Success !';exit 0
}
if [[ -f $settings_file ]];then # going to parse the settings file
	OlD="$IFS";IFS=$'\n';for line in $(cat $settings_file | sed -E 's/.*=( +)?//g' 2>/dev/null);do
		case $line_number in
			1 ) player=$line;;
			2 ) for written_site in $(echo $line | sed -E "s#\{|'|\}|,##g");do SITES[${#SITES[@]}]="$written_site";done;;
			* ) break;;
		esac;((line_number++))
	done;IFS="$OlD"
else
	notify-send "Settings File not Found .. !";read -p "You haven't created your settings file .. Do you want to create it ? ";
	if IsYes $REPLY; then create_settings_file;sudo nano $settings_file;notify-send 'Done !'
	else echo 'Then, The Default settings are going to be used this time ..';fi
fi
player=${player=mplayer};recursive=false # Adding defaults and initializing variables
if [[ ${#SITES[@]} == 0 ]];then SITES=('http://ccmixter.org/view/media/samples/mixed');fi # If no Site was specified in the settings file
while getopts rsvu opt;do # Getting options
	case $opt in
		r) recursive=true;; # The variable for checking wether to play music recursively or not ..
		s ) sudo rm '/etc/PlayMusic.settings' &>/dev/null;create_settings_file;notify-send "Settings File Recreated Successfully !";exit 0;;
		v ) read -p 'Editor ? ';sudo $REPLY '/etc/PlayMusic.settings';exit 0;;
		u ) read -p 'Are you sure you want to UnInstall ? ';if IsYes $REPLY;then UNINSTALL;fi;;
	esac
done
function Play { # Function for playing music according to user preferences
	if $2 && [[ ${#1} -lt 23 ]];then notify-send "Now Playing $1 .." "$track";fi # Notifing the user,only if he'll play freely ( $2 ) & the track's name isn't too long
	if $recursive && $2;then while true;do $player "$1";done;else $player "$1";fi # Playing, according to user preferences
}
function Find { 
	echo "Looking for '$1' on disk .. "; # Informing the user, if that's going to take long ( which depends on the contents of his home directory )
	FILE=$(find ~ -name "$1.mp3" 2>/dev/null) # The main file ( the found file, or null if not found ) ..
	[[ -n $FILE ]] && FILE2=$(find ~ -name "$1.mp3.st" 2>/dev/null) # The state file ( used for resuming in axel )
	clear # Just clear, so that the user doesn't see the first message if the finding operation went quickly ..
}
declare -A Tracks;clear;echo 'Loading Sites ..'
for SITE in $SITES;do # Looping through all sites specified
	for site in $(lynx -source "$SITE" | egrep -o 'http://.*\.mp3');do # Grabbing all music links ( newline delimeted )
		name="$(echo $site | sed -Ee 's/_/ /g' -e 's#.*/##g' -e 's#.*- ##g' -e 's#.mp3##g' -e 's#.*%2D ##g')" # Filtering names out of sites ..
		Tracks[$name]="$site" # Adding the name as the key, and the site as the value
	done
done;clear # Clear anything there is on the screen ( It should be already cleared, so this re-positions the view if the user changed it ( which is very likely ) ) ..
if [[ ${#Tracks[@]} == 0 ]];then echo 'No Music was Found !';fi # Just in Case ;)
select track in "${!Tracks[@]}";do
	[[ -n $track ]] || continue # Continues the loop if choice is empty ( meaning that user's choice wasn't appropriate ) ..
	clear;echo 'What do you want to do ?';name="$track.mp3" # Setting the name and asking the user ..
	select choice in "Download then Play" "Just Play Online";do [[ -n $choice ]] || continue # ( already demonstrated )
		if [[ $choice == "Download then Play" ]];then # Instead of the case statement ( since this offers only two options )
			Find "$track" # Looking for the specified track on disk
			not_complete=$([[ -n $FILE2 ]] && echo true || echo false) # Checking wether it's complete or not
			sayer=$($not_complete && echo "Append to that file" || echo "ReDownload the file") # what to say ..
			if [[ -n $FILE ]] ;then # if the track was found on disk
				[[ $(dirname "$FILE") == "$HOME/Music" ]] || { # if the found file is not in the music directory
					notify-send "$track was found at ($(dirname $FILE)) and was moved to ($HOME/Music)" # inform the user of the changes
					mv "$FILE" "$HOME/Music";FILE="$HOME/Music/$name" # move the file to the music home directory
				};echo -e "\"$track\" was found !\n\t What do you want to do ?" # tell the user about the found file
				select choice2 in "Just $sayer" "Play that instead";do [[ -n $choice2 ]] || continue # tell him what to do
					case $choice2 in
						"Just $sayer") name="$FILE"; $not_complete || rm "$FILE";break;;
						* ) Play "$FILE" true;exit 0;;
					esac
				done
			fi;notify-send "Downloading ($track) .." "in [ $PWD ] ..";axel -a -o "$name" "${Tracks[$track]}" && Play "$name" true # Download & Play
		else Play "${Tracks[$track]}" true # Play Online
		fi;break
	done;break
done;exit 0
