.TH PlayMusic 1 "24 April 2014" "1.0" "PlayMusic Manual"
.SH NAME
PlayMusic - Play/Download Music
.SH SYNOPSIS
.B PlayMusic
.RI [OPTIONS]
.br
.SH DESCRIPTION
\fPPlayMusic\fP is a simple entertainment utility that is made mainly for music lovers .. It Can \fPplay music online\fP, \fPdownload it\fP .. and provide you with \fPthe newest music\fP from sites provided in the \fPsettings file\fP .. ( also it can be \fPeasily extended\fP as a bash script )
.SH OPTIONS
.IP \fB\-r\fP
Play Music Recursively ..
.IP \fB\-s\fP
ReCreate the Settings File ..
.IP \fB\-u\fP
UnInstall 'PlayMusic' ..
.IP \fB\-v\fP
View Settings File ..
.SH SEE ALSO
wget(1), lynx(1), mplayer(1)
.SH BUGS
No Known Bugs ..
.SH AUTHOR
Amr Ayman (miroamr78@gmail.com)
